---
- name: Ash AS3 PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    uri_method: POST

  vars_files:
    - ../creds/bigip_creds.yaml

  tasks:
  
  - name: Create BIGIP Base Configuration
    uri:
      url: https://35.176.153.176/mgmt/shared/appsvcs/declare
      user: "{{ bigip_user }}"
      password: "{{ bigip_pass }}"
      method: "{{ uri_method }}"
      body: "{{ lookup('file','as3-declaration.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: as3_response

  # - name: Debug out entire AS3 response
  #   debug:
  #     msg: "{{ as3_response }}"

  - name: Debug out AS3 Virtual Server response
    debug:
      msg: "{{ as3_response.json.declaration.ashlewis.A1.service.virtualAddresses }}"

...